// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Iavra_MZ_Localization_byNeomaStudio","status":false,"description":"Convert to MZ by Wisarut Perunawin แปลงเวอร์ชั่น MZ โดย วิศรุต เปรุนาวิน\r\n<Iavra_MZ_Localization_byNeomaStudio>","parameters":{"Escape Code":"#{{key}}","Languages":"en","File Path":"{lang}.json","Option Label":"Language","Language Labels":"en:English"}},
{"name":"dahlys_jumptolabel","status":false,"description":"","parameters":{}},
{"name":"readFromJson","status":true,"description":"","parameters":{}},
{"name":"multipleLineChoices","status":true,"description":"Enables multiline choices","parameters":{}},
{"name":"forageScoreHandler","status":true,"description":"","parameters":{}},
{"name":"CGMZ_Core","status":false,"description":"Core CGMZ Plugin, should be placed above all other CGMZ Plugins.","parameters":{"Check for Updates":"true","Dev Tools on Start":"false","Show FPS Counter":"false","Fullscreen":"false","Simulate Production Env":"false"}},
{"name":"CGMZ_MenuCommandWindow","status":false,"description":"Manage the menu command window","parameters":{"Commands":"[]","Alignment":"center","Keep Original Commands":"true","Enable Text Codes":"true"}},
{"name":"helperFunctions","status":true,"description":"","parameters":{}},
{"name":"Theo_PathfindingMZ","status":true,"description":"v1.0.1 - Pathfinding, move route generator.","parameters":{}},
{"name":"sirL_MPskipText","status":true,"description":"This plugin is composed of multiple plugins. If problem report it with debug hash which can be found in Help section to the generator page.","parameters":{"Control Skip Text":"","cST.skipableText":"true"}}
];
